pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                echo "Test stage"
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                echo "Delivery state"
                // sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('Completed ') {
            steps {
                echo "Job Complete!."
            }
        }
    }
}
